### ISSUE TITLE
Encoding?

### ISSUE THREAD

**Issue by Leont** [TestAnything/Specification#12]
We really should specify what kind of encoding TAP uses. Currently it seems to be effectively ASCII, but I would argue to mandate it being UTF-8.

**Comment by kinow** [comment]
Even though I use ISO-8859-1 in some applications, it's quite easy encode it to UTF-8 - and even a good idea when serializing the data and working with other systems.

@Leont, I *think* that in JUnit the encoding is defined in the XML header. So I assume users are free to choose which one they'd like to use. Do you have an argument on why TAP should enforce one over others? 

ps: I'm not a specialist in encoding, so I apologize beforehand if I'm saying anything stupid here :)

**Comment by Leont** [comment]
> Do you have an argument on why TAP should enforce one over others? 

1. Having variable encoding would complicate the parsing (because it has to switch mid-stream), which may involve reparsing.
2. Supporting other encodings would not add any new capabilities: UTF-8 can express any other encoding, the reverse is not the case for other (non-unicode) encodings
3. The list of other encodings is open ended, it may lead to parsers not being able to read a TAP stream because they're not familiar with some encodings.
4. UTF-8 is [increasingly](http://w3techs.com/technologies/details/en-utf8/all/all) the world wide [standard](http://utf8everywhere.org/) for text encodings.

**Comment by kinow** [comment]
These all seem like good arguments to me (again, not a specialist :-) ). I'm +1 for it too. Let's see if somebody will have other suggestions.

**Comment by jcelliott** [comment]
UTF-8 seems like the obvious choice here. +1 from me.

**Comment by beatgammit** [comment]
+1 for UTF-8

**Comment by jonathanKingston** [comment]
I say go for UTF7 encoding with a GSM charset that will really put the beginners off.

As @Leont said, the only choice here is UTF8. UTF16 has some merit in other cultures but can be solved just as well by UTF8.

I think for now a strict mandate of UTF8 is fine as will back port to ASCII just fine. If producers care about performance that can be a problem for another day which could be resolved in many other ways.
