### ISSUE TITLE
Collaboration structure

### ISSUE THREAD

**Issue by smikes** [TestAnything/Specification#19]
@isaacs when you are at the point of setting up a working group, I'd like to be involved.  Currently working w/ TAP in a non-perl non-JS context.

**Comment by isaacs** [comment]
Thanks!  Sorry, been busy with a bunch of other things, but I'll try to get to this soon.  Where are you working with TAP that isn't JS or Perl?

**Comment by smikes** [comment]
Working on test runners for Swift - https://developer.apple.com/swift/blog/?id=29

**Comment by ranford** [comment]
I also work with TAP in a non-Perl non JS environment:

http://www.mathworks.com/help/matlab/ref/matlab.unittest.plugins.tapplugin-class.html

http://blogs.mathworks.com/developer/2015/01/29/tap-plugin/

We are continuing to work in this area so j am also interested in staying close.


Andy

[Sent from my phone]

**Comment by isaacs** [comment]
See https://github.com/TestAnything/Specification/issues/20
