### ISSUE TITLE
Collaboration towards a formal specification and future governance

### ISSUE THREAD

**Issue by isaacs** [TestAnything/Specification#20]
Sorry for the long delay.

I've created a slack channel at https://testanything.slack.com for faster collaboration towards a formal specification and a working group to own it moving forward.  Everyone mentioned in this thread whose emails I could find on GitHub has an invite.

@ranford @xmojmr, You both have hidden email addresses on GitHub and no public git activity.  If you'd like an invite, email i@izs.me and I'll set you up.

If we decide that slack isn't a useful channel, then that's fine.  I've seen it be very useful for other teams, and I think it'd be a better format to move this project forward.

**Comment by smikes** [comment]
"We couldn't find an account matching smikes@cubane.com" ?

**Comment by TheAlphaNerd** [comment]
@isaacs would you be able to send me an invite?

**Comment by Leont** [comment]
The channel used to have a lot of implementation related discussion that really should have been a different channel (even if it may be in the same organization). I zoned out on the signal-to-noise ratio.

Combined with general slow responses (specially from people like me who don't use slack for other purposes so have to explicitly log in), I'm not sure it's the right medium.

**Comment by marcbachmann** [comment]
@isaacs Was there any progress on the new format/spec?

**Comment by isaacs** [comment]
See https://github.com/TestAnything/Specification/pull/25

We're gonna JFDI.  If there's quorum among implementors, that's the spec.
