### ISSUE TITLE
Hyphens between test number and description?

### ISSUE THREAD

**Issue by riddochc** [TestAnything/Specification#21]
In most of the examples in the TAP specification, there's a hyphen between the test number and the description of the test, but the text of the spec doesn't mention it as a separator.

Nothing says it *should* be there, but the fact that it is, and consistently so, suggests that it may be an artifact of some common TAP output.  Worth looking into, anyway.

**Comment by Leont** [comment]
Yeah, I know of multiple outputters that use it and Test::Harness and TAP::Harness parse it away (but doesn't require it). I'm not 100% sure but I think other parsers do the same.

**Comment by exodist** [comment]
test::more and friends in perl have always used it. nice to know it is not required. imagine a bunch lf parsers will fail without it.

**Comment by jonathanKingston** [comment]
I think it has mostly been ambiguous but @Leont is correct that it is basically part of the text description for the test.

**Comment by jonathanKingston** [comment]
I suggest moving this to the Slack discussion that @isaacs has setup as this isn't currently something the spec can solve until it TAP 13 comes out. Even then it will likely just further clarify the document.

**Comment by isaacs** [comment]
https://github.com/TestAnything/Specification/pull/25/files#diff-1fdb6f17d18295d39b8a3ee5b260374867993b9306f3130b7df76627c60615c7R320-R323
