### ISSUE TITLE
Exit code responsibility

### ISSUE THREAD

**Issue by Jameskmonger** [TestAnything/Specification#22]
Whose responsibility is it to return the correct exit code based on whether there were failing tests?

Is it the responsibility of the producer or the parser?

**Comment by kinow** [comment]
I think this is not covered in the specification - as far as I can recall - but I'd guess if parser or producer find an error, both should emit an error. In tap4j, both will throw exceptions, but it's up to the caller code to decide whether the exception should result in some exit code.

A more complete example could be the Jenkins TAP plug-in. Whether tap4j parser/producer find errors, the plug-in is catching those errors and, based on user configuration, marking builds as stable/unstable/failed.

Hope it helps.

**Comment by jonathanKingston** [comment]
Yup not defined. Depends on the use case obviously a consumer could be a web interface etc. Probably makes sense to return a sane exit code for a producer however again that could be HTTPS based service too. TAP is a format not a protocol so it's really down to implementation.

From what I remember the latest spec is removing all protocol specific bits that should have never been in there like mentions to environment variables.

**Comment by Leont** [comment]
Sounds like we need a core spec, and an appendix with guidelines how to use it in practice.

**Comment by jamesrichford** [comment]
Hi there guys,

Has there been any developments on this issue?

**Comment by isaacs** [comment]
Clarified in TAP14 draft, in progress currently. https://github.com/TestAnything/Specification/pull/25/files#diff-1fdb6f17d18295d39b8a3ee5b260374867993b9306f3130b7df76627c60615c7R110-R122
