### ISSUE TITLE
Test Point descriptions containing "#"

### ISSUE THREAD

**Issue by isaacs** [TestAnything/Specification#26]
I think the `Comment` rule appears only here? But isn't a `TestPoint` with a comment valid too?

```tap
ok 1 - test # comment
```

Or is that part of the `Description`? I think `Description` is missing here too?

_Originally posted by @kinow in https://github.com/TestAnything/Specification/pull/25#discussion_r817365996_

**Comment by isaacs** [comment]
Here are some annoying edge cases:

```tap
TAP version 13
ok 1 - description # contains a hash
ok 2 - description # contains a hash # todo
ok 3 - description # todo handle # edge cases
1..3
```

Questions for implementors:

1. What do your implementations do today?  (Which of these, if any, are marked `TODO`, what is the description/reason for each test point?)
2. What do you think they _should_ do? (Ie, is the current behavior a bug you'd fix, if reported?)
3. Is there already a way in your framework for a user to have a test that contains a `#` character, without being confusing?

---

Proposal for (3):

1. Adopt `\#` as a way to escape the `#` in a test point description, so:

    ```tap
    ok 1 - description \# todo
    ```

    would be a non-TODO test point with a description of `"description # todo"`

2. If we can escape `#` with `\`, then we have to be able to escape `\` with `\` as well, no?  So `ok 1 - description \\# todo` would be a `TODO` test point with a description of `description \`

Pros: once you have the Harness parsing it like this, then the Producer can just `s/#/\\#/g` in the description field, and everything Just Works on both ends.
Cons: `\`-escaping code in parsers is always a minor bug factory, especially if you can escape `\`. (But at least it's not uncommon or unfamiliar?  Most of us have probably written this code dozens of times already.)

So then the "correct" unambiguous way to do this would be:

```tap
TAP version 13

# test with # in the description
ok 1 - description \# contains a hash

# todo test with a # in the Description
ok 2 - description \# contains a hash # todo

# todo test with a # in the Reason
ok 3 - description # todo handle \# edge cases
1..3
```

---

Zooming in on these two:

```tap
ok 2 - description # contains a hash # todo
ok 3 - description # todo handle # edge cases
```

- Is it the _last_ `#` that's important here?
- Or the first?
- Or just the instance(s) of `# todo` (ie, known directives) specifically?

---

For myself: node-tap/tap-parser's behavior here is absolutely bonkers, I'm embarrassed by it, I intend to fix it, and I'm willing to just copy whatever anyone else tells me so that we have quorum and get the spec done 😅 

@exodist @mblayman @kinow @Leont

**Comment by isaacs** [comment]
From https://github.com/TestAnything/Specification/pull/25#discussion_r818225358 @mblayman 

In my reading of the TAP13 spec in the [Directives section](https://testanything.org/tap-version-13-specification.html#directives), the language used was "*starts with* # TODO". In tappy, I took this to mean:

* The first `#` is the start of a directive.
* There can be only one recognized directive per test point.
* Only TODO and SKIP are recognized (with the appropriate case sensitivity and permission of characters after "SKIP" like "Skipped" applied)

The language in the spec calls the stuff after as "explanation" or "reason" depending on the context, so I normalized that part as a "description."

Given all that, I think I would lean toward using the second to last bullet to recognize only a single directive and treat everything after it as the description. Things that don't look like a TODO or SKIP would be an unknown directive (or ignored outright).

**Comment by isaacs** [comment]
From https://github.com/TestAnything/Specification/pull/25#discussion_r819889570 @Leont

> Specify a way to escape # chars, so they're not parsed as directives, and say that producers should escape any # characters in test descriptions. (This seems like a good idea regardless, but I'm not sure if there's consensus on it. Node-tap will not parse directives that use \ to escape the #.)

Test::Harness allows for `#`(or `\`) to be escaped with `\`, and has done so since at least 2007. I'm pretty sure some stuff depends on that.

**Comment by isaacs** [comment]
So it seems like the escaping proposal is at least supported by Perl for a decade and a half.  Node-tap's parser does this, just has some obvious bugs that I'll get fixed, but shouldn't hold up the spec.  ✅

@mblayman 

> Given all that, I think I would lean toward using the second to last bullet to recognize only a single directive and treat everything after it as the description. Things that don't look like a TODO or SKIP would be an unknown directive (or ignored outright).

So then, IIUC:

```tap
TAP version 13

# { id: 1, description: "description", directive: "# contains a hash", todo: false }
ok 1 - description # contains a hash

# { id: 2, description: "description", directive: "# contains a hash # todo", todo: false }
ok 2 - description # contains a hash # todo

# { id: 3, description: "description", directive: "# todo handle # edge cases", todo: true, todoReason: "handle # edge cases"}
ok 3 - description # todo handle # edge cases
1..3
```

yes?

**Comment by Leont** [comment]
> What do your implementations do today? (Which of these, if any, are marked TODO, what is the description/reason for each test point?)

It would fail to parse

> What do you think they should do? (Ie, is the current behavior a bug you'd fix, if reported?)

It should fail to parse

> Is there already a way in your framework for a user to have a test that contains a # character, without being confusing?
Yes, \-escaping as mentioned before

**Comment by mblayman** [comment]
> ```
> TAP version 13
> 
> # { id: 1, description: "description", directive: "# contains a hash", todo: false }
> ok 1 - description # contains a hash
> 
> # { id: 2, description: "description", directive: "# contains a hash # todo", todo: false }
> ok 2 - description # contains a hash # todo
> 
> # { id: 3, description: "description", directive: "# todo handle # edge cases", todo: true, todoReason: "handle # edge cases"}
> ok 3 - description # todo handle # edge cases
> 1..3
> ```
> 
> yes?

That's pretty close to what tappy would do. The TAP13 spec says "Directives are special notes that *follow* a # on the test line" (emphasis added). To that end, tappy doesn't include `#\s*` as part of the directive, but this is a minor detail that's not super important to me.

**Comment by isaacs** [comment]
Awesome.  Just updated mine to do the same: https://github.com/tapjs/tap-parser/commit/1fe6bb880f8e646f52284686504a46289986d2d2

Calling this quorum :+1:

> tappy doesn't include #\s* as part of the directive, but this is a minor detail that's not super important to me.

Yeah, npm:tap-parser doesn't either, was just including that to mean "This is the part that you are treating as the directive bits that you're parsing", but the spec intentionally doesn't dictate how parsers reflect that to their users, since that's so contextual anyway.
