### ISSUE TITLE
Repeated test point IDs

### ISSUE THREAD

**Issue by isaacs** [TestAnything/Specification#27]
What do y'all do with this:

```tap
TAP version 13
ok 1
ok 1
ok 1
1..3
```

Is that valid TAP?  Is it passing?

I notice that node-tap just lets you output the same Test Point ID repeatedly, and doesn't complain about it.  Since the common TAP producers in JS land (node-tap, tape, mocha, and jest) all _don't_ re-use Test Point IDs, this has never come up as a problem, but I do have a bash test script I've used that outputs test point IDs in random order, so it'd be nice to have a check that all the tests got run.

Can we add something like this to the spec?

```markdown
Test Point IDs _should_ be unique within the TAP Document.  Harnesses _may_
warn about repeated Test Point IDs or treat them as a test failure, but
_must not_ treat a Test Point with a re-used ID as a non-TAP line.
```

**Comment by kinow** [comment]
I think _should_ sounds correct. In `tap4j` IIRC there is a strictness flag, which I would use it to let users to decide whether to see a warning or get an error when these are repeated.

And I wouldn't expect to see repeated test point IDs, unless the user is using subtests (but I think this is out of TAP13 and TAP14? and the test plan and/or indentation would help in that case I reckon)

**Comment by Leont** [comment]
Test::Harness will warn if they're not a proper sequence

**Comment by isaacs** [comment]
> And I wouldn't expect to see repeated test point IDs, unless the user is using subtests (but I think this is out of TAP13 and TAP14?

Subtexts will be in tap14, just not drafted yet. Going step by step.

**Comment by mblayman** [comment]
The proposed spec language looks good to me. tappy will accept number any number currently, but warning about uniqueness sounds like a good addition.

**Comment by isaacs** [comment]
@Leont whats a "proper sequence"? In order? Or just fully covered?

**Comment by Leont** [comment]
> whats a "proper sequence"? In order? Or just fully covered?

In order

**Comment by isaacs** [comment]
> In order. Or to be precise: the number needs to match the number of observed test results.

So would these be allowed?

```tap
TAP version 13
1..3
ok
ok 3
ok 2
```

```tap
TAP version 13
1..3
ok 2
ok 3
ok
```

```tap
TAP version 13
1..3
ok
ok 3
ok 3
```

**Comment by isaacs** [comment]
Node-tap will now allow the first two, but complain about the second, because the test is 3 is repeated.

**Comment by Leont** [comment]
> So would these be allowed?

None of them would, but this would:
```
ok
ok 2
ok 3
```
Or 
```
ok 1
ok 
ok 3
```

**Comment by isaacs** [comment]
@Leont Cool, then that's a bit _more_ strict than the proposed language, but still well within it, so I'll keep it.  Thanks for confirming!
