### ISSUE TITLE
whitespace before directive?

### ISSUE THREAD

**Issue by isaacs** [TestAnything/Specification#28]
Can I get a ruling on this?

```tap
TAP version 13
# this should be a skip test, obviously
ok 1 - description # skip

# no whitespace after #, is this skipped?
ok 2 - description #skip

# no whitespace before #, is this skipped?
ok 3 - description# skip

# no whitespace anywhere, is this skipped?
ok 4 - description#skip

# no description, whitespace after
ok 5 # skip

# no description, no whitespace after
ok 6 #skip

1..6
```

If we already effectively require (or wish to require) whitespace surrounding the `#` character, then we can specify the directive parsing much more simply, because there's no way it could ever be escaped with `\`.

ping @mblayman @exodist @leont @kinow

**Comment by kinow** [comment]
IMO:

```
TAP version 13
# this should be a skip test, obviously 🙆🏻
ok 1 - description # skip

# no whitespace after #, is this skipped? 🙅🏻
ok 2 - description #skip

# no whitespace before #, is this skipped?🙅🏻
ok 3 - description# skip

# no whitespace anywhere, is this skipped?🙅🏻
ok 4 - description#skip

# no description, whitespace after🙆🏻
ok 5 # skip

# no description, no whitespace after🙅🏻
ok 6 #skip

1..6
```
Just because it's simpler to tokenize/parse with a space before and after, and I think making the description optional would be fine too.

**Comment by Leont** [comment]
Main produces in Perl and Raku output spaces before and after.
Two consumers accept `#` with or without spaces before or after it, one of them (Test2::Harness) gives warnings if the spaces are missing (but will otherwise parse it)

**Comment by mblayman** [comment]
tappy considers all 6 as skips and doesn't really care about the whitespace before or after.

```bash
(venv) ➜  tappy git:(main) tap skip_whitespace.tap 
ssssss
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK (skipped=6)
```
I don't have strong feelings about this topic. If we think it would be easier to make a valid consumer by expecting more whitespace, that seems fine to me.

**Comment by isaacs** [comment]
Thanks everyone.  In the interest of "specify what we have", how does this sound:

1. Producers _must_ output `\s+#\s+${directive}` for directives
2. Harnesses _must not_ treat `\\#\s*\S+` as a directive (escaped)
3. Harnesses _must_ treat `\s#\s+\S+` as a directive
4. Harnesses _may_ treat `\S#\s+\S+`, `\s#\S+`, or `\S#\S+` as a directive, but _should_ warn that this is invalid.

I think if that's how we specify it, then everyone is compliant, and there's still some decent guidance for new consumers (they don't _have_ to support anything other than `ok 1 - name # skip`, but they can if they want to).

**Comment by isaacs** [comment]
I'll try to make the language more precise than this and provide examples, of course.
