### ISSUE TITLE
Highlight innovations of TAP14 in the text of specification 

### ISSUE THREAD

**Issue by ligurio** [TestAnything/Specification#33]
TAP13 is a simple and well-known format for testing results. TAP14 is based on TAP13 format with a number if innovations. I believe it would be helpful for readers to highlight new things in comparison to previous version. For example change background for sentences that was added to existed sections and mark with tag "New!" added sections.

**Comment by isaacs** [comment]
This is a great idea.  Maybe the 14 pec could also have a "summary of changes from TAP 13" up front somewhere?

**Comment by isaacs** [comment]
@ligurio Feedback welcome on #40. Thanks!
