### ISSUE TITLE
Pragmas

### ISSUE THREAD

**Issue by Leont** [TestAnything/Specification#6]
Perl 5's TAP parser contains a mechanism called pragmas in its TAP13 mode. This basically means that the stream can subtly change some aspects of how it is parsed. The only supported pragma is strict, which causes any unknown lines to be parse errors.

This may be a useful mechanism to standardize.

**Comment by jonathanKingston** [comment]
+1 definitely this is worth having.

I would like to have another that causes the parser to trigger a fatal exception on first error also. Combined with strict this would stop parsing after the first unknown character.

**Comment by kinow** [comment]
I didn't know it existed :D my +1

**Comment by Leont** [comment]
> I didn't know it existed :D my +1

I haven't seen anything actually use it, it's not documented either. It's barely existent really.

**Comment by jonathanKingston** [comment]
I think this mostly answers #4 which is a benefit actually.

**Comment by Leont** [comment]
The format currently used seems to be

    pragma +strict, -somethingelse

Which is sensible enough to me.

**Comment by Leont** [comment]
> I think this mostly answers #4 which is a benefit actually.

Yeah, I was about to say just that in that ticket.

**Comment by jonathanKingston** [comment]
@Leont @kinow please consider all new additional parser hints as a `pragma` and mark the tickets accordingly. (We can run with this name I think as there is no opposition and is in current use already)

**Comment by jonathanKingston** [comment]
It does however strike me as something that the caller of the c would like to enable over it coming out of the TAP itself - I think we should account for this in that the caller and consumers can override.

Also mentioned in #4 is how the call order happens, should the pragma only be at the top of the document or are these flags able to be used like this:
```
...
ok 12 - reason
pragma +strict
ok 13 - important test
ok 14 - something
pragma -strict
ok 15 - less important
```

I would prefer that the pragmas are resolved before the parsing happens for ease of use however I think the question is worth resolving now.

**Comment by beatgammit** [comment]
> I would prefer that the pragmas are resolved before the parsing happens for ease of use however I think the question is worth resolving now.

I agree. It's easier to allow it later if there's ever a need.

**Comment by jonathanKingston** [comment]
@beatgammit I'm not sure it it would be easy to add it in later without breaking a lot of consumers. I am however fairly certain it is hard to see a use for it.

**Comment by beatgammit** [comment]
I guess I was more thinking of processing old output, not generating new output. But you're right, it would be easier to go the otherway (allow it everywhere, later restrict it).

**Comment by jonathanKingston** [comment]
@Leont so if I am right unknown lines streamed through the TAP parser with the strict parser get converted into errors? Sorry I'm not seeing the functionality immediately from the code itself.

**Comment by isaacs** [comment]
https://github.com/TestAnything/Specification/pull/25

**Comment by isaacs** [comment]
node-tap only supports `strict` at present as well, but I intend to add `bail` simply because it's the other flag the parser responds to.
