### ISSUE TITLE
Agree upon a mime type

### ISSUE THREAD

**Issue by jonathanKingston** [TestAnything/Specification#7]
Out of the discussions of #1 it was decided that a common mime type would be useful in the specification.

This is a discussion around that, as I see it the most suitable is `application/tap`.

- thanks @beatgammit

**Comment by kinow** [comment]
+1 for application/tap

**Comment by jonathanKingston** [comment]
Suggested change:

# Recommended Media Type Usage
When streaming TAP across a network it is MAY be possible to provide a MIME type for content negotiation.
The suggested MIME type to transfer TAP documents is `application/tap`

---

I suggest parking the negotiation of `tap-archive` as mentioned in #1 its an edge case that we can populate later, the discussion would require talk about the compression chosen like: `application/tap-archive+tar`

**Comment by Leont** [comment]
`application/tap` sounds fine to me

**Comment by jonathanKingston** [comment]
This is now in the `tap-14-specification` branch. Please let me know if there are any issues.
Thanks
